In [1]:
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier

In [2]:
play = pd.read_csv("https://gist.githubusercontent.com/bigsnarfdude/515849391ad37fe593997fe0db98afaa/raw/f663366d17b7d05de61a145bbce7b2b961b3b07f/weather.csv")

In [3]:
play

outlook temperature humidity  windy play
0   overcast         hot     high  False  yes
1   overcast        cool   normal   True  yes
2   overcast        mild     high   True  yes
3   overcast         hot   normal  False  yes
4      rainy        mild     high  False  yes
5      rainy        cool   normal  False  yes
6      rainy        cool   normal   True   no
7      rainy        mild   normal  False  yes
8      rainy        mild     high   True   no
9      sunny         hot     high  False   no
10     sunny         hot     high   True   no
11     sunny        mild     high  False   no
12     sunny        cool   normal  False  yes
13     sunny        mild   normal   True  yes

In [4]:
clfMLP = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(5, 2), random_state=123)

In [5]:
dummies1 = pd.get_dummies(play, columns=['temperature'], prefix = ['Dummy'])

In [6]:
dummies2 = pd.get_dummies(play, columns=['play'], prefix = ['Dummy'])

In [7]:
dummiesPlay = pd.DataFrame(zip(dummies1.Dummy_hot, dummies1.Dummy_mild,dummies2.Dummy_yes))
dummiesPlay.columns =['DHot', 'DMild', 'DYes']

In [8]:
dummiesPlay

DHot  DMild  DYes
0      1      0     1
1      0      0     1
2      0      1     1
3      1      0     1
4      0      1     1
5      0      0     1
6      0      0     0
7      0      1     1
8      0      1     0
9      1      0     0
10     1      0     0
11     0      1     0
12     0      0     1
13     0      1     1

In [9]:
X = dummiesPlay[['DHot','DMild']]

In [10]:
y = dummiesPlay[['DYes']]

In [11]:
clfMLP.fit(X, np.ravel(y))

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=123,
              solver='lbfgs')

In [12]:
clfMLP.coefs_

[array([[ 0.36378804, -0.39599061, -0.50576977,  0.09501591,  0.40637511],
        [-0.14237831,  0.89019693,  0.3422361 , -0.03530704, -0.19975833]]),
 array([[ 0.44067919, -0.58790752],
        [-0.60094294,  0.05842144],
        [ 0.05893288,  0.24886071],
        [ 0.64701804,  0.41560799],
        [ 0.20557435,  0.41188262]]),
 array([[-0.768583  ],
        [-0.58346126]])]

In [13]:
clfMLP.predict([[0,0], [0, 1]])

array([1, 1])