In [1]:
# Load the NumPy package
import numpy as np

In [2]:
# Create an array
array1 = np.array([[1,2],[3,4]])
array1

array([[1, 2],
       [3, 4]])

In [3]:
# Return a flattened array
np.reshape(array1, (1,4))

array([[1, 2, 3, 4]])

In [4]:
# Create another array
array2 = np.array([[1,2],[3,4],[5,6]])
array2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
# Reshapes array to a 2 by 3 array
np.ravel(array2)

array([1, 2, 3, 4, 5, 6])

In [6]:
# Resize array to a 2 by 3 array
np.resize(array2,(2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# Transposes the array
np.transpose(array2)

array([[1, 3, 5],
       [2, 4, 6]])