In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
housing = pd.read_csv('txhousing.csv')

In [3]:
housing

city  year  month  sales      volume  median  listings  \
0                 Abilene  2015      6    260    41396230  141500       965   
1                Amarillo  2015      6    342    61748196  152100      1213   
2               Arlington  2015      6    522   105881452  180000       682   
3                  Austin  2015      6   3301  1086689918  270200      7419   
4                Bay Area  2015      6    780   182248573  200700      2116   
5                Beaumont  2015      6    296    48007961  145200      1567   
6         Brazoria County  2015      6    137    25772571  173100       285   
7             Brownsville  2015      6     82    11833474  115000       744   
8   Bryan-College Station  2015      6    403    84025416  187400       939   
9           Collin County  2015      6   1789   614959441  300400      2314   
10         Corpus Christi  2015      6    493   104904076  189600      2133   
11                 Dallas  2015      6   6532  1960556658  242300     11014   
12          Denton County  2015      6   1125   306978637  238000      1635   
13                El Paso  2015      6    689   118116401  147700      4105   
14              Fort Bend  2015      6   1341   429731131  284200      3166   
15             Fort Worth  2015      6   1287   248314498  159300      2221   
16              Galveston  2015      6    111    27475690  206900       635   
17                Garland  2015      6    212    35772714  154800       208   
18              Harlingen  2015      6     93    12099797  120800      1724   
19                Houston  2015      6   8449  2490238594  222400     22311   
20                 Irving  2015      6    194    46433702  193300       325   
21              Kerrville  2015      6     81    16859871  175000       648   
22      Killeen-Fort Hood  2015      6    277    41102980  135900      1361   
23                 Laredo  2015      6    106    18468901  154300       556   
24      Longview-Marshall  2015      6    254    43893511  149400      1889   
25                Lubbock  2015      6    425    72529370  141400      1047   
26                 Lufkin  2015      6     70    12051050  160000       408   
27                McAllen  2015      6    170    21855944  118000      2175   
28                Midland  2015      6    218    63667557  257700       797   
29      Montgomery County  2015      6   1032   350936735  256300      3305   
30            Nacogdoches  2015      6     36     5718840  140000       291   
31      NE Tarrant County  2015      6   1128   364781158  241400      1451   
32                 Odessa  2015      6    107    20320574  176800       245   
33                  Paris  2015      6     49     6238350  121100       290   
34            Port Arthur  2015      6     79    10864768  118900       513   
35             San Angelo  2015      6    158    31155867  175400       547   
36            San Antonio  2015      6   2919   701375402  199400      9105   
37             San Marcos  2015      6     39     8808027  190000       101   
38        Sherman-Denison  2015      6    163    25104282  130000       534   
39     South Padre Island  2015      6     40     8665950  166700       728   
40          Temple-Belton  2015      6    213    35933886  148900       858   
41              Texarkana  2015      6    152    22132772  131100       701   
42                  Tyler  2015      6    422    82254422  170000      2574   
43               Victoria  2015      6    100    18920746  174300       299   
44                   Waco  2015      6    280    49171360  151800       999   
45          Wichita Falls  2015      6    143    18820752  118800       770   

    inventory         date  
0         5.0  2015.416667  
1         4.4  2015.416667  
2         1.6  2015.416667  
3         2.8  2015.416667  
4         3.2  2015.416667  
5         6.7  2015.416667  
6         2.6  2015.416667  
7        10.7  2015.416667  
8         3.5  2015.416667  
9         1.7  20

In [4]:
X = housing[['sales']]
y = housing[['median']]

In [5]:
# Create training and testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=123)

# Scale the input features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
y_train = scaler.fit_transform(y_train)

In [6]:
# Initialize and fit a linear svr model to training data
svr_lin = SVR(kernel='poly', degree=2, C = 0.1, epsilon = 1.1)
svr_lin.fit(np.reshape(X_train,(-1,1)), np.ravel(y_train))

SVR(C=0.1, degree=2, epsilon=1.1, kernel='poly')

In [7]:
np.linspace(0.1, 0.4, 6)

array([0.1 , 0.16, 0.22, 0.28, 0.34, 0.4 ])

In [8]:
svr_lin.predict(np.reshape(np.random.normal(0, 1, 5),(-1,1)))

array([0.11619683, 0.57148103, 0.19536741, 0.11551453, 0.25438376])

In [9]:
np.random.normal(0, 1, 20)

array([-1.11211833, -0.35207361, -0.212809  , -0.19045265,  0.12371574,
       -0.79600783,  0.59699675, -0.83555971, -1.20767068,  0.82911875,
        0.37247012,  1.09836702, -0.80923144, -0.58447562,  0.23231632,
        0.82718465,  0.92918172,  0.17580246, -1.47332762, -0.53984807])

In [10]:
print(svr_lin)

SVR(C=0.1, degree=2, epsilon=1.1, kernel='poly')


In [14]:
svr_lin.predict(np.reshape([-1.11211833, -0.35207361, -0.212809  , -0.19045265,  0.12371574,-0.79600783,  0.59699675, -0.83555971, -1.20767068,  0.82911875,
        0.37247012,  1.09836702, -0.80923144, -0.58447562,  0.23231632,
        0.82718465,  0.92918172,  0.17580246, -1.47332762, -0.53984807],(-1,1))

SyntaxError: unexpected EOF while parsing (1131357656.py, line 4)

In [15]:
array = [1.37460487,-1.38276878,2.0829424,0.21345689, -1.21033951,0.18506318,0.56063398,0.42868309,-1.38872698,0.01743677,-1.37647729,-0.68148206,-0.1794263 ,-0.40175439,  0.96515971,-2.21100338, -0.18564737,  0.06678801,  0.40305024,  0.17529709]

In [18]:
svr_lin.predict(np.reshape(array,(-1,1)))

array([0.25059029, 0.2523508 , 0.44212647, 0.10637963, 0.21738253,
       0.10549469, 0.12739734, 0.11718817, 0.25364223, 0.10284002,
       0.25099315, 0.1391367 , 0.105334  , 0.11543927, 0.17566813,
       0.48513116, 0.10551162, 0.10316509, 0.11552084, 0.10521945])